### ISSUE TITLE
CodeDeploy is stuck in middle of pre-validation step and then rolls back

### ISSUE THREAD

**Issue by AlexSun98** [davidgf/serverless-plugin-canary-deployments#32]
CodeDeploy is stuck in middle of pre-validation step and then rolls back.

any clue?

**Comment by AlexSun98** [comment]
I am trying to deploy a bunch of lambda functions via this lib and serverless framework. CodeDeploy is stuck in middle of pre-validation step and then rolls back.

**Comment by davidgf** [comment]
If you attach a hook to your deployment preferences, you need to call the CodeDeploy `putLifecycleEventHookExecutionStatus` method with the validation result in the timeframe of one hour, otherwise it'll assume the deployment failed. You can check how the hook function should look in the [hooks.js file of the examples directory](https://github.com/davidgf/serverless-plugin-canary-deployments/blob/master/example/hooks.js)
