### ISSUE TITLE
Not do traffic shifting?

### ISSUE THREAD

**Issue by revmischa** [davidgf/serverless-plugin-canary-deployments#58]
Love the plugin - but is there a way to use the pre/post traffic hook but not the traffic shifting? I want the canary option but not to wait a long time for every deployment; sometimes I need to deploy things quickly.

Thanks!

P.S. it doesn't seem to be creating the CodeDeploy IAM policy automatically for me:
```
[ERROR] ClientError: An error occurred (AccessDeniedException) when calling the PutLifecycleEventHookExecutionStatus operation: User: arn:aws:sts::898466151470:assumed-role/myapp-mish-eu-central-1-lambdaRole/myapp-mish-preHookCanary is not authorized to perform: codedeploy:PutLifecycleEventHookExecutionStatus on resource: arn:aws:codedeploy:eu-central-1:898466741470:deploymentgroup:myapp-mish-myappmishDeploymentApplication-DP39TAO2TZ28/myapp-mish-AppLambdaFunctionDeploymentGroup-FUGL97F0ZMEU
Traceback (most recent call last):
  File "/var/task/myapp/handler/canary.py", line 33, in pre_traffic_handler
    codedeploy.put_lifecycle_event_hook_execution_status(**params)
  File "/var/runtime/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 623, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

**Comment by davidgf** [comment]
Hey Mischa, I'm glad you find it useful :) You could use `AllAtOnce` as deployment type (instead of `Canary10Percent5Minutes`, for example), which basically executes the pre hook, shifts all the traffic to the new function and runs the post hook afterwards.
Regarding the policy issue, the plugin automatically includes all the permissions CodeDeploy needs to change Lambda settings, but it doesn't add permissions for Lambda to perform any CodeDeploy actions, which are needed only if you have a pre/post hook. This would be a really nice addition, PRs are welcome :smile:

**Comment by revmischa** [comment]
Ok thanks, will try it
